export const NETWORK_ERROR = 'NETWORK_ERROR';
export const INTERNAL_ERROR = 'INTERNAL_ERROR';
export const AUTHENTICATION_INVALID_TOKEN = 'AUTHENTICATION_INVALID_TOKEN';
export const AUTHENTICATION_EXPIRED_TOKEN = 'AUTHENTICATION_EXPIRED_TOKEN';
export const SERVER_ERROR = 'SERVER_ERROR';

